### ISSUE TITLE
nogui option for start-vmx

### ISSUE THREAD

**Issue by bjoernbessert** [bottkars/vmxtoolkit#1]
Hi,

when i start a VM with start-vmx, the VM is registered in VMware Workstation GUI and focussed.

If i try to remove the VM later with remove-vmx, the following error occurs:

```
PS S:\VMs> get-vmx -Path 'S:\VMs' .\id8348384-mssql01 | remove-vmx
WARNUNG: Error: This VM is in use. Please close VMX id8348384-mssql01 in Vmware UI and try again
WARNUNG: id8348384-mssql01
WARNUNG: Error: This VM is in use.
```

If "vmrun start ..." is called with "nogui" parameter, the VM isn't registered in the GUI and "remove-vmx" succeeds.

I can't fully close VMware Workstation GUI (because other VM's are running) and besides that, we want to fully automate VM startup and removal.

Therefore, i would like to propose an option to choose the nogui parameter.

Or is there another option in "remove-vmx" to deregister/remove the VM?

**Comment by bottkars** [comment]
will add this by tomorow !

**Comment by bottkars** [comment]
added to harmony
