### ISSUE TITLE
Github not linked on Powershell Gallery

### ISSUE THREAD

**Issue by thorstenkampe** [bottkars/vmxtoolkit#12]
This repository is not linked at https://www.powershellgallery.com/packages/vmxtoolkit/4.5.1 on the left side under "Project Site" making the Github repository hard to find.

**Comment by bottkars** [comment]
i still maintain compatiobility to powershell 3.0. ProjectUri is a 5.0 psd tag, that would require an update of the modulemanifest and thus break in 3.0. will add the url do the description get-help -online might take you to my old homepage. nthere are some changes planned for 5.0 with documentation on readthedocs similar to http://labbuildr.readthedocs.io/en/master/
