### ISSUE TITLE
Wrong "default vmxdir" (virtual machine directory) values on import

### ISSUE THREAD

**Issue by thorstenkampe** [bottkars/vmxtoolkit#16]
On import the value for "default vmxdir" is incorrectly computed:
```
 ==>default vmxdir is F:\cygwin\home\thorsten\Documents\Virtual Machines\
```
The correct value is in `$env:APPDATA\preferences.ini` (on Windows): `prefvmx.defaultVMPath`. `vmxtoolkit` should be able to use that value.

**Comment by bottkars** [comment]
fixed in 4.5.3.1
