### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by JLogan3o13** [bottkars/vmxtoolkit#20]
I have just stumbled upon this project, and while it seems promising, there are a lot of issues I am finding. My first question is whether this is still actively being developed, or if the contributors have moved on. I don't want to bombard the page with requests if no one is working on this any longer. Below are just a few of the issues I have seen since downloading yesterday; the vast majority of which are in the documentation and consistency areas:

- Of the 72 functions, 17 have no online help page:
   Add-VMXScsiDisk
   convert-VMXdos2unix
   Copy-VMXDirHost2Guest
   copy-VMXfile2guest
   Get-VMXRun
   Get-VMXscenario
   Invoke-VMXBash
   Invoke-VMXexpect
   Invoke-VMXPowerShell
   New-VMXGuestPath
   New-VMXScsiDisk
   remove-vmx
   Remove-VMXserial
   Search-VMXPattern
   Set-VMXscenario
   Set-VMXserialPipe
   Set-VMXVnet

- Of the 55 functions left, 23 have no online help page and just redirect to the main Wiki page
- An additional 3 are straight-up broken links (Get-VMXAnnotation, Set-VMXDisplayName, Set-VMXMEMFile)
- Add additional 3 have no page and just redirect back to the main labbuilr.bottnet.de/modules page

This means that, of 72 functions, only 26 have viable online help pages.

Regardless of whether they have an online page or not, the majority of the help pages are unclear, and do not contain examples. Just a few of the many examples I have found:
   - Set-VMXDisplayName: has an example referencing a variable ($value1) but this var is never fully explained. The help page states ("..a valid config file") but does not explain that this would be the VM's .vmx file. It also does not show an example of using Get-VMX to get the config file and then piping that to this function, which would be the most common way people would use it. This is also one of the broken links, so someone searching for this is left scouring Google for someone who has already figured it out.

   - Set-VMXMainMemory: this is a mess - no explanation on the function, the help page references the Set-VMXMEMFile online page, but that page too is a broken link.

   - New-VMXSCSIDisk: No explanation of the format for the disk size other than that it is a long. No examples of usage, so the typical user is not going to understand that just putting in 20 for the -NewDiskSize parameter will throw an error; and with the weak documentation they are not going to know you actually have to put the GB after the number for it to work. Also, if they do stumble upon the correct syntax, trying to create anything above 2000GB the script will throw an error, with no good explanation in the help page the user is left to wonder why. 

Again, these are just a few issues I have notice having downloaded the project yesterday. If someone is actively working the project it would be great to see some of these addressed for the community. If not, I will simply download source and fix them for my own use.

**Comment by bottkars** [comment]
Yes, the process is still maintained by the author. Unfortunately, there was a plan to move the documentation to readthedocs in version 5.
There are some examples on https://community.emc.com/blogs/azurestack_guy/2015/06/11/labbuildrtipps-and-tricks-for-vmxtoolkit-labbuildr-and-labtools and even in the labbuildr code, that should explain the usage.

However, I given my current limited time an the fact people spend their time on searching for irrelevant thinhs to complain about rather than contributing, I leave it just to real bug fixing right now. There are inline helps and explanation, and value validation is there for good reason. 

Contributing starts with creating stuff
