### ISSUE TITLE
-config option in add-vmxscsidisk and other cmdlets

### ISSUE THREAD

**Issue by davehardy20** [bottkars/vmxtoolkit#4]
Hi I'm following your help for running windows nano server in vmware, I get stopped when the add-vmxscsidisk cmdlet asks for config

[16:10:32][C:\Users\daveh|# Add-VMXScsiDisk -Controller 0 -LUN 0 -Diskname '$TargetVM.vmdk'
cmdlet Add-VMXScsiDisk at command pipeline position 1
Supply values for the following parameters:
config: 

What is the required value of config??

Also the config option seems to be required in other cmdlets, could you please update the wiki or post the config option requirements

Thanks

Dave

**Comment by bottkars** [comment]
-config is always the path to the .vmx file, wich hold the config. allows pipeline from get-vmx

**Comment by davehardy20** [comment]
thanks, works now.

however the nano server I created following your instructions fails to boot
error message says;

file: \windows\system32\drivers\vmci.sys

Info, says the driver is missing, although I injected the drivers
successfully

I'm using vmware workstation 12 maybe this could be the issue.

Any thoughts on this?

Dave

On 19 November 2015 at 20:08, Karsten Bott <notifications@github.com> wrote:

> -config is always the path to the .vmx file, wich hold the config. allows
> pipeline from get-vmx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bottkars/vmxtoolkit/issues/4#issuecomment-158182810>.
>



-- 
Best Regards
David Hardy

Follow Me on Twitter @davehardy20 <http://twitter.com/davehardy20> LinkedIn
Profile <http://uk.linkedin.com/pub/david-hardy/6/388/2a2> pentest-N00b Blog
<http://pentestn00b.wordpress.com/>
