### ISSUE TITLE
Error in line 1721 Character 19

### ISSUE THREAD

**Issue by jrlopezs** [bottkars/vmxtoolkit#5]
Hi,
The script are reporting the following error:

The expression following the '&' in a pipeline element produced an invalid object. The result should be a command name, a script block or CommandInfo object.
En C:\Users\admin\Documents\vmxtoolkit-master\vmxtoolkit.psm1: 1721 Character: 19
+         (($cmdresult = &$vmrun List) 2>&1 | Out-Null)
+                                   ~~~~~~                         
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

Thanks so much for your hard work to bring us this awesome tool.

**Comment by Rincevent76** [comment]
Same error here, only it's on line 1763 : 19
+         (($cmdresult = &$vmrun List) 2>&1 | Out-Null)
+                         ~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

**Comment by bottkars** [comment]
How di you load the modules ? wich was the command you were using when it showed up ?
![image](https://cloud.githubusercontent.com/assets/8255007/16405526/9e41474c-3d08-11e6-9780-d378503cf5ab.png)
if modulkes are not loaded / initialized, it wil fail anyway.

**Comment by Rincevent76** [comment]
You are right I mis-imported the module (tried to import the psm1 file instead of the psd1 file) now it works, thanks a lot for yout help !

**Comment by bottkars** [comment]
you can for eas of use, just import the upper level directory without tariling \, eg ipmo c:\vmxtoolkit

**Comment by Rincevent76** [comment]
thxs for the tip, will use it for sure (I'm just starting with powershell)
